// Code generated by MockGen. DO NOT EDIT.
// Source: plugins/types/types.go
//
// Generated by this command:
//
//	mockgen -source=plugins/types/types.go -destination=plugins/types/mocks/mock_types.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	config "github.com/ecos-labs/ecos/code/cli/config"
	types "github.com/ecos-labs/ecos/code/cli/plugins/types"
	gomock "go.uber.org/mock/gomock"
)

// MockPlugin is a mock of Plugin interface.
type MockPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPluginMockRecorder
	isgomock struct{}
}

// MockPluginMockRecorder is the mock recorder for MockPlugin.
type MockPluginMockRecorder struct {
	mock *MockPlugin
}

// NewMockPlugin creates a new mock instance.
func NewMockPlugin(ctrl *gomock.Controller) *MockPlugin {
	mock := &MockPlugin{ctrl: ctrl}
	mock.recorder = &MockPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlugin) EXPECT() *MockPluginMockRecorder {
	return m.recorder
}

// Description mocks base method.
func (m *MockPlugin) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockPluginMockRecorder) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockPlugin)(nil).Description))
}

// Execute mocks base method.
func (m *MockPlugin) Execute(ctx context.Context, arg1 map[string]any) (*types.PluginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, arg1)
	ret0, _ := ret[0].(*types.PluginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockPluginMockRecorder) Execute(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPlugin)(nil).Execute), ctx, arg1)
}

// Name mocks base method.
func (m *MockPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPlugin)(nil).Name))
}

// Type mocks base method.
func (m *MockPlugin) Type() types.PluginType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(types.PluginType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockPluginMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockPlugin)(nil).Type))
}

// Validate mocks base method.
func (m *MockPlugin) Validate(arg0 map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockPluginMockRecorder) Validate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockPlugin)(nil).Validate), arg0)
}

// Version mocks base method.
func (m *MockPlugin) Version() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(string)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockPluginMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockPlugin)(nil).Version))
}

// MockCorePlugin is a mock of CorePlugin interface.
type MockCorePlugin struct {
	ctrl     *gomock.Controller
	recorder *MockCorePluginMockRecorder
	isgomock struct{}
}

// MockCorePluginMockRecorder is the mock recorder for MockCorePlugin.
type MockCorePluginMockRecorder struct {
	mock *MockCorePlugin
}

// NewMockCorePlugin creates a new mock instance.
func NewMockCorePlugin(ctrl *gomock.Controller) *MockCorePlugin {
	mock := &MockCorePlugin{ctrl: ctrl}
	mock.recorder = &MockCorePluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCorePlugin) EXPECT() *MockCorePluginMockRecorder {
	return m.recorder
}

// Author mocks base method.
func (m *MockCorePlugin) Author() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Author")
	ret0, _ := ret[0].(string)
	return ret0
}

// Author indicates an expected call of Author.
func (mr *MockCorePluginMockRecorder) Author() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Author", reflect.TypeOf((*MockCorePlugin)(nil).Author))
}

// Description mocks base method.
func (m *MockCorePlugin) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockCorePluginMockRecorder) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockCorePlugin)(nil).Description))
}

// Documentation mocks base method.
func (m *MockCorePlugin) Documentation() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Documentation")
	ret0, _ := ret[0].(string)
	return ret0
}

// Documentation indicates an expected call of Documentation.
func (mr *MockCorePluginMockRecorder) Documentation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Documentation", reflect.TypeOf((*MockCorePlugin)(nil).Documentation))
}

// Execute mocks base method.
func (m *MockCorePlugin) Execute(ctx context.Context, arg1 map[string]any) (*types.PluginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, arg1)
	ret0, _ := ret[0].(*types.PluginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCorePluginMockRecorder) Execute(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCorePlugin)(nil).Execute), ctx, arg1)
}

// IsCore mocks base method.
func (m *MockCorePlugin) IsCore() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCore")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCore indicates an expected call of IsCore.
func (mr *MockCorePluginMockRecorder) IsCore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCore", reflect.TypeOf((*MockCorePlugin)(nil).IsCore))
}

// Name mocks base method.
func (m *MockCorePlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockCorePluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockCorePlugin)(nil).Name))
}

// Type mocks base method.
func (m *MockCorePlugin) Type() types.PluginType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(types.PluginType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockCorePluginMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockCorePlugin)(nil).Type))
}

// Validate mocks base method.
func (m *MockCorePlugin) Validate(arg0 map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockCorePluginMockRecorder) Validate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockCorePlugin)(nil).Validate), arg0)
}

// Version mocks base method.
func (m *MockCorePlugin) Version() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(string)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockCorePluginMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockCorePlugin)(nil).Version))
}

// MockIngestPlugin is a mock of IngestPlugin interface.
type MockIngestPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockIngestPluginMockRecorder
	isgomock struct{}
}

// MockIngestPluginMockRecorder is the mock recorder for MockIngestPlugin.
type MockIngestPluginMockRecorder struct {
	mock *MockIngestPlugin
}

// NewMockIngestPlugin creates a new mock instance.
func NewMockIngestPlugin(ctrl *gomock.Controller) *MockIngestPlugin {
	mock := &MockIngestPlugin{ctrl: ctrl}
	mock.recorder = &MockIngestPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIngestPlugin) EXPECT() *MockIngestPluginMockRecorder {
	return m.recorder
}

// Author mocks base method.
func (m *MockIngestPlugin) Author() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Author")
	ret0, _ := ret[0].(string)
	return ret0
}

// Author indicates an expected call of Author.
func (mr *MockIngestPluginMockRecorder) Author() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Author", reflect.TypeOf((*MockIngestPlugin)(nil).Author))
}

// DataSource mocks base method.
func (m *MockIngestPlugin) DataSource() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataSource")
	ret0, _ := ret[0].(string)
	return ret0
}

// DataSource indicates an expected call of DataSource.
func (mr *MockIngestPluginMockRecorder) DataSource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataSource", reflect.TypeOf((*MockIngestPlugin)(nil).DataSource))
}

// Description mocks base method.
func (m *MockIngestPlugin) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockIngestPluginMockRecorder) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockIngestPlugin)(nil).Description))
}

// Documentation mocks base method.
func (m *MockIngestPlugin) Documentation() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Documentation")
	ret0, _ := ret[0].(string)
	return ret0
}

// Documentation indicates an expected call of Documentation.
func (mr *MockIngestPluginMockRecorder) Documentation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Documentation", reflect.TypeOf((*MockIngestPlugin)(nil).Documentation))
}

// Execute mocks base method.
func (m *MockIngestPlugin) Execute(ctx context.Context, arg1 map[string]any) (*types.PluginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, arg1)
	ret0, _ := ret[0].(*types.PluginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockIngestPluginMockRecorder) Execute(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockIngestPlugin)(nil).Execute), ctx, arg1)
}

// FetchData mocks base method.
func (m *MockIngestPlugin) FetchData(arg0 map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchData", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// FetchData indicates an expected call of FetchData.
func (mr *MockIngestPluginMockRecorder) FetchData(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchData", reflect.TypeOf((*MockIngestPlugin)(nil).FetchData), arg0)
}

// IsCore mocks base method.
func (m *MockIngestPlugin) IsCore() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCore")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCore indicates an expected call of IsCore.
func (mr *MockIngestPluginMockRecorder) IsCore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCore", reflect.TypeOf((*MockIngestPlugin)(nil).IsCore))
}

// Name mocks base method.
func (m *MockIngestPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockIngestPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockIngestPlugin)(nil).Name))
}

// ProcessData mocks base method.
func (m *MockIngestPlugin) ProcessData(arg0 map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessData", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessData indicates an expected call of ProcessData.
func (mr *MockIngestPluginMockRecorder) ProcessData(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessData", reflect.TypeOf((*MockIngestPlugin)(nil).ProcessData), arg0)
}

// StoreData mocks base method.
func (m *MockIngestPlugin) StoreData(arg0 map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreData", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreData indicates an expected call of StoreData.
func (mr *MockIngestPluginMockRecorder) StoreData(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreData", reflect.TypeOf((*MockIngestPlugin)(nil).StoreData), arg0)
}

// Type mocks base method.
func (m *MockIngestPlugin) Type() types.PluginType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(types.PluginType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockIngestPluginMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockIngestPlugin)(nil).Type))
}

// Validate mocks base method.
func (m *MockIngestPlugin) Validate(arg0 map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockIngestPluginMockRecorder) Validate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockIngestPlugin)(nil).Validate), arg0)
}

// ValidateConnection mocks base method.
func (m *MockIngestPlugin) ValidateConnection(arg0 map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateConnection", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateConnection indicates an expected call of ValidateConnection.
func (mr *MockIngestPluginMockRecorder) ValidateConnection(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateConnection", reflect.TypeOf((*MockIngestPlugin)(nil).ValidateConnection), arg0)
}

// Version mocks base method.
func (m *MockIngestPlugin) Version() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(string)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockIngestPluginMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockIngestPlugin)(nil).Version))
}

// MockInitPlugin is a mock of InitPlugin interface.
type MockInitPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockInitPluginMockRecorder
	isgomock struct{}
}

// MockInitPluginMockRecorder is the mock recorder for MockInitPlugin.
type MockInitPluginMockRecorder struct {
	mock *MockInitPlugin
}

// NewMockInitPlugin creates a new mock instance.
func NewMockInitPlugin(ctrl *gomock.Controller) *MockInitPlugin {
	mock := &MockInitPlugin{ctrl: ctrl}
	mock.recorder = &MockInitPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInitPlugin) EXPECT() *MockInitPluginMockRecorder {
	return m.recorder
}

// Author mocks base method.
func (m *MockInitPlugin) Author() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Author")
	ret0, _ := ret[0].(string)
	return ret0
}

// Author indicates an expected call of Author.
func (mr *MockInitPluginMockRecorder) Author() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Author", reflect.TypeOf((*MockInitPlugin)(nil).Author))
}

// CloudProvider mocks base method.
func (m *MockInitPlugin) CloudProvider() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloudProvider")
	ret0, _ := ret[0].(string)
	return ret0
}

// CloudProvider indicates an expected call of CloudProvider.
func (mr *MockInitPluginMockRecorder) CloudProvider() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloudProvider", reflect.TypeOf((*MockInitPlugin)(nil).CloudProvider))
}

// CreateDirectoryStructure mocks base method.
func (m *MockInitPlugin) CreateDirectoryStructure() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDirectoryStructure")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDirectoryStructure indicates an expected call of CreateDirectoryStructure.
func (mr *MockInitPluginMockRecorder) CreateDirectoryStructure() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDirectoryStructure", reflect.TypeOf((*MockInitPlugin)(nil).CreateDirectoryStructure))
}

// CreateResources mocks base method.
func (m *MockInitPlugin) CreateResources() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResources")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateResources indicates an expected call of CreateResources.
func (mr *MockInitPluginMockRecorder) CreateResources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResources", reflect.TypeOf((*MockInitPlugin)(nil).CreateResources))
}

// Description mocks base method.
func (m *MockInitPlugin) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockInitPluginMockRecorder) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockInitPlugin)(nil).Description))
}

// Documentation mocks base method.
func (m *MockInitPlugin) Documentation() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Documentation")
	ret0, _ := ret[0].(string)
	return ret0
}

// Documentation indicates an expected call of Documentation.
func (mr *MockInitPluginMockRecorder) Documentation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Documentation", reflect.TypeOf((*MockInitPlugin)(nil).Documentation))
}

// DownloadTransformModels mocks base method.
func (m *MockInitPlugin) DownloadTransformModels() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadTransformModels")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadTransformModels indicates an expected call of DownloadTransformModels.
func (mr *MockInitPluginMockRecorder) DownloadTransformModels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadTransformModels", reflect.TypeOf((*MockInitPlugin)(nil).DownloadTransformModels))
}

// Execute mocks base method.
func (m *MockInitPlugin) Execute(ctx context.Context, arg1 map[string]any) (*types.PluginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, arg1)
	ret0, _ := ret[0].(*types.PluginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockInitPluginMockRecorder) Execute(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockInitPlugin)(nil).Execute), ctx, arg1)
}

// GenerateConfig mocks base method.
func (m *MockInitPlugin) GenerateConfig() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateConfig")
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateConfig indicates an expected call of GenerateConfig.
func (mr *MockInitPluginMockRecorder) GenerateConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateConfig", reflect.TypeOf((*MockInitPlugin)(nil).GenerateConfig))
}

// InitializeBaseFiles mocks base method.
func (m *MockInitPlugin) InitializeBaseFiles() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeBaseFiles")
	ret0, _ := ret[0].(error)
	return ret0
}

// InitializeBaseFiles indicates an expected call of InitializeBaseFiles.
func (mr *MockInitPluginMockRecorder) InitializeBaseFiles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeBaseFiles", reflect.TypeOf((*MockInitPlugin)(nil).InitializeBaseFiles))
}

// IsCore mocks base method.
func (m *MockInitPlugin) IsCore() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCore")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCore indicates an expected call of IsCore.
func (mr *MockInitPluginMockRecorder) IsCore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCore", reflect.TypeOf((*MockInitPlugin)(nil).IsCore))
}

// Name mocks base method.
func (m *MockInitPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockInitPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockInitPlugin)(nil).Name))
}

// PostInitSummary mocks base method.
func (m *MockInitPlugin) PostInitSummary() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostInitSummary")
	ret0, _ := ret[0].(error)
	return ret0
}

// PostInitSummary indicates an expected call of PostInitSummary.
func (mr *MockInitPluginMockRecorder) PostInitSummary() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostInitSummary", reflect.TypeOf((*MockInitPlugin)(nil).PostInitSummary))
}

// RunInteractiveSetup mocks base method.
func (m *MockInitPlugin) RunInteractiveSetup() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInteractiveSetup")
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInteractiveSetup indicates an expected call of RunInteractiveSetup.
func (mr *MockInitPluginMockRecorder) RunInteractiveSetup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInteractiveSetup", reflect.TypeOf((*MockInitPlugin)(nil).RunInteractiveSetup))
}

// SetModelVersion mocks base method.
func (m *MockInitPlugin) SetModelVersion(version string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetModelVersion", version)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetModelVersion indicates an expected call of SetModelVersion.
func (mr *MockInitPluginMockRecorder) SetModelVersion(version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetModelVersion", reflect.TypeOf((*MockInitPlugin)(nil).SetModelVersion), version)
}

// SupportedEngines mocks base method.
func (m *MockInitPlugin) SupportedEngines() []types.EngineOption {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportedEngines")
	ret0, _ := ret[0].([]types.EngineOption)
	return ret0
}

// SupportedEngines indicates an expected call of SupportedEngines.
func (mr *MockInitPluginMockRecorder) SupportedEngines() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportedEngines", reflect.TypeOf((*MockInitPlugin)(nil).SupportedEngines))
}

// SupportedTransformTools mocks base method.
func (m *MockInitPlugin) SupportedTransformTools() []types.TransformToolOption {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportedTransformTools")
	ret0, _ := ret[0].([]types.TransformToolOption)
	return ret0
}

// SupportedTransformTools indicates an expected call of SupportedTransformTools.
func (mr *MockInitPluginMockRecorder) SupportedTransformTools() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportedTransformTools", reflect.TypeOf((*MockInitPlugin)(nil).SupportedTransformTools))
}

// Type mocks base method.
func (m *MockInitPlugin) Type() types.PluginType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(types.PluginType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockInitPluginMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockInitPlugin)(nil).Type))
}

// Validate mocks base method.
func (m *MockInitPlugin) Validate(arg0 map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockInitPluginMockRecorder) Validate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockInitPlugin)(nil).Validate), arg0)
}

// ValidatePrerequisites mocks base method.
func (m *MockInitPlugin) ValidatePrerequisites() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePrerequisites")
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidatePrerequisites indicates an expected call of ValidatePrerequisites.
func (mr *MockInitPluginMockRecorder) ValidatePrerequisites() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePrerequisites", reflect.TypeOf((*MockInitPlugin)(nil).ValidatePrerequisites))
}

// ValidateRegion mocks base method.
func (m *MockInitPlugin) ValidateRegion(region string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRegion", region)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateRegion indicates an expected call of ValidateRegion.
func (mr *MockInitPluginMockRecorder) ValidateRegion(region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRegion", reflect.TypeOf((*MockInitPlugin)(nil).ValidateRegion), region)
}

// Version mocks base method.
func (m *MockInitPlugin) Version() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(string)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockInitPluginMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockInitPlugin)(nil).Version))
}

// MockTransformPlugin is a mock of TransformPlugin interface.
type MockTransformPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockTransformPluginMockRecorder
	isgomock struct{}
}

// MockTransformPluginMockRecorder is the mock recorder for MockTransformPlugin.
type MockTransformPluginMockRecorder struct {
	mock *MockTransformPlugin
}

// NewMockTransformPlugin creates a new mock instance.
func NewMockTransformPlugin(ctrl *gomock.Controller) *MockTransformPlugin {
	mock := &MockTransformPlugin{ctrl: ctrl}
	mock.recorder = &MockTransformPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransformPlugin) EXPECT() *MockTransformPluginMockRecorder {
	return m.recorder
}

// Author mocks base method.
func (m *MockTransformPlugin) Author() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Author")
	ret0, _ := ret[0].(string)
	return ret0
}

// Author indicates an expected call of Author.
func (mr *MockTransformPluginMockRecorder) Author() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Author", reflect.TypeOf((*MockTransformPlugin)(nil).Author))
}

// BuildConfig mocks base method.
func (m *MockTransformPlugin) BuildConfig(ecosConfig any, command string, args []string) map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildConfig", ecosConfig, command, args)
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// BuildConfig indicates an expected call of BuildConfig.
func (mr *MockTransformPluginMockRecorder) BuildConfig(ecosConfig, command, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildConfig", reflect.TypeOf((*MockTransformPlugin)(nil).BuildConfig), ecosConfig, command, args)
}

// Description mocks base method.
func (m *MockTransformPlugin) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockTransformPluginMockRecorder) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockTransformPlugin)(nil).Description))
}

// Documentation mocks base method.
func (m *MockTransformPlugin) Documentation() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Documentation")
	ret0, _ := ret[0].(string)
	return ret0
}

// Documentation indicates an expected call of Documentation.
func (mr *MockTransformPluginMockRecorder) Documentation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Documentation", reflect.TypeOf((*MockTransformPlugin)(nil).Documentation))
}

// Execute mocks base method.
func (m *MockTransformPlugin) Execute(ctx context.Context, arg1 map[string]any) (*types.PluginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, arg1)
	ret0, _ := ret[0].(*types.PluginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockTransformPluginMockRecorder) Execute(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockTransformPlugin)(nil).Execute), ctx, arg1)
}

// ExecuteCommand mocks base method.
func (m *MockTransformPlugin) ExecuteCommand(ctx context.Context, command string, args []string, arg3 map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteCommand", ctx, command, args, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteCommand indicates an expected call of ExecuteCommand.
func (mr *MockTransformPluginMockRecorder) ExecuteCommand(ctx, command, args, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteCommand", reflect.TypeOf((*MockTransformPlugin)(nil).ExecuteCommand), ctx, command, args, arg3)
}

// GetProjectPath mocks base method.
func (m *MockTransformPlugin) GetProjectPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetProjectPath indicates an expected call of GetProjectPath.
func (mr *MockTransformPluginMockRecorder) GetProjectPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectPath", reflect.TypeOf((*MockTransformPlugin)(nil).GetProjectPath))
}

// GetSupportedCommands mocks base method.
func (m *MockTransformPlugin) GetSupportedCommands() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupportedCommands")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSupportedCommands indicates an expected call of GetSupportedCommands.
func (mr *MockTransformPluginMockRecorder) GetSupportedCommands() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportedCommands", reflect.TypeOf((*MockTransformPlugin)(nil).GetSupportedCommands))
}

// IsCore mocks base method.
func (m *MockTransformPlugin) IsCore() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCore")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCore indicates an expected call of IsCore.
func (mr *MockTransformPluginMockRecorder) IsCore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCore", reflect.TypeOf((*MockTransformPlugin)(nil).IsCore))
}

// Name mocks base method.
func (m *MockTransformPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockTransformPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockTransformPlugin)(nil).Name))
}

// PrepareEnvironment mocks base method.
func (m *MockTransformPlugin) PrepareEnvironment(ctx context.Context, arg1 map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareEnvironment", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PrepareEnvironment indicates an expected call of PrepareEnvironment.
func (mr *MockTransformPluginMockRecorder) PrepareEnvironment(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareEnvironment", reflect.TypeOf((*MockTransformPlugin)(nil).PrepareEnvironment), ctx, arg1)
}

// ShowCommandHelp mocks base method.
func (m *MockTransformPlugin) ShowCommandHelp(command string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowCommandHelp", command)
	ret0, _ := ret[0].(error)
	return ret0
}

// ShowCommandHelp indicates an expected call of ShowCommandHelp.
func (mr *MockTransformPluginMockRecorder) ShowCommandHelp(command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowCommandHelp", reflect.TypeOf((*MockTransformPlugin)(nil).ShowCommandHelp), command)
}

// TransformEngine mocks base method.
func (m *MockTransformPlugin) TransformEngine() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransformEngine")
	ret0, _ := ret[0].(string)
	return ret0
}

// TransformEngine indicates an expected call of TransformEngine.
func (mr *MockTransformPluginMockRecorder) TransformEngine() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransformEngine", reflect.TypeOf((*MockTransformPlugin)(nil).TransformEngine))
}

// Type mocks base method.
func (m *MockTransformPlugin) Type() types.PluginType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(types.PluginType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockTransformPluginMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockTransformPlugin)(nil).Type))
}

// Validate mocks base method.
func (m *MockTransformPlugin) Validate(arg0 map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockTransformPluginMockRecorder) Validate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockTransformPlugin)(nil).Validate), arg0)
}

// ValidateEnvironment mocks base method.
func (m *MockTransformPlugin) ValidateEnvironment(arg0 map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateEnvironment", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateEnvironment indicates an expected call of ValidateEnvironment.
func (mr *MockTransformPluginMockRecorder) ValidateEnvironment(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateEnvironment", reflect.TypeOf((*MockTransformPlugin)(nil).ValidateEnvironment), arg0)
}

// Version mocks base method.
func (m *MockTransformPlugin) Version() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(string)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockTransformPluginMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockTransformPlugin)(nil).Version))
}

// MockDestroyPlugin is a mock of DestroyPlugin interface.
type MockDestroyPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockDestroyPluginMockRecorder
	isgomock struct{}
}

// MockDestroyPluginMockRecorder is the mock recorder for MockDestroyPlugin.
type MockDestroyPluginMockRecorder struct {
	mock *MockDestroyPlugin
}

// NewMockDestroyPlugin creates a new mock instance.
func NewMockDestroyPlugin(ctrl *gomock.Controller) *MockDestroyPlugin {
	mock := &MockDestroyPlugin{ctrl: ctrl}
	mock.recorder = &MockDestroyPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDestroyPlugin) EXPECT() *MockDestroyPluginMockRecorder {
	return m.recorder
}

// DestroyResources mocks base method.
func (m *MockDestroyPlugin) DestroyResources() ([]types.DestroyResourceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyResources")
	ret0, _ := ret[0].([]types.DestroyResourceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DestroyResources indicates an expected call of DestroyResources.
func (mr *MockDestroyPluginMockRecorder) DestroyResources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyResources", reflect.TypeOf((*MockDestroyPlugin)(nil).DestroyResources))
}

// Name mocks base method.
func (m *MockDestroyPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockDestroyPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockDestroyPlugin)(nil).Name))
}

// ValidatePrerequisites mocks base method.
func (m *MockDestroyPlugin) ValidatePrerequisites() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePrerequisites")
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidatePrerequisites indicates an expected call of ValidatePrerequisites.
func (mr *MockDestroyPluginMockRecorder) ValidatePrerequisites() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePrerequisites", reflect.TypeOf((*MockDestroyPlugin)(nil).ValidatePrerequisites))
}

// MockConfigurableDestroyPlugin is a mock of ConfigurableDestroyPlugin interface.
type MockConfigurableDestroyPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockConfigurableDestroyPluginMockRecorder
	isgomock struct{}
}

// MockConfigurableDestroyPluginMockRecorder is the mock recorder for MockConfigurableDestroyPlugin.
type MockConfigurableDestroyPluginMockRecorder struct {
	mock *MockConfigurableDestroyPlugin
}

// NewMockConfigurableDestroyPlugin creates a new mock instance.
func NewMockConfigurableDestroyPlugin(ctrl *gomock.Controller) *MockConfigurableDestroyPlugin {
	mock := &MockConfigurableDestroyPlugin{ctrl: ctrl}
	mock.recorder = &MockConfigurableDestroyPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigurableDestroyPlugin) EXPECT() *MockConfigurableDestroyPluginMockRecorder {
	return m.recorder
}

// DescribeDestruction mocks base method.
func (m *MockConfigurableDestroyPlugin) DescribeDestruction() []types.DestroyResourcePreview {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeDestruction")
	ret0, _ := ret[0].([]types.DestroyResourcePreview)
	return ret0
}

// DescribeDestruction indicates an expected call of DescribeDestruction.
func (mr *MockConfigurableDestroyPluginMockRecorder) DescribeDestruction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDestruction", reflect.TypeOf((*MockConfigurableDestroyPlugin)(nil).DescribeDestruction))
}

// DestroyResources mocks base method.
func (m *MockConfigurableDestroyPlugin) DestroyResources() ([]types.DestroyResourceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyResources")
	ret0, _ := ret[0].([]types.DestroyResourceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DestroyResources indicates an expected call of DestroyResources.
func (mr *MockConfigurableDestroyPluginMockRecorder) DestroyResources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyResources", reflect.TypeOf((*MockConfigurableDestroyPlugin)(nil).DestroyResources))
}

// LoadFromConfig mocks base method.
func (m *MockConfigurableDestroyPlugin) LoadFromConfig(cfg *config.EcosConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadFromConfig", cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadFromConfig indicates an expected call of LoadFromConfig.
func (mr *MockConfigurableDestroyPluginMockRecorder) LoadFromConfig(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFromConfig", reflect.TypeOf((*MockConfigurableDestroyPlugin)(nil).LoadFromConfig), cfg)
}

// Name mocks base method.
func (m *MockConfigurableDestroyPlugin) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockConfigurableDestroyPluginMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockConfigurableDestroyPlugin)(nil).Name))
}

// ValidatePrerequisites mocks base method.
func (m *MockConfigurableDestroyPlugin) ValidatePrerequisites() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePrerequisites")
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidatePrerequisites indicates an expected call of ValidatePrerequisites.
func (mr *MockConfigurableDestroyPluginMockRecorder) ValidatePrerequisites() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePrerequisites", reflect.TypeOf((*MockConfigurableDestroyPlugin)(nil).ValidatePrerequisites))
}

// MockDestroyConfigLoader is a mock of DestroyConfigLoader interface.
type MockDestroyConfigLoader struct {
	ctrl     *gomock.Controller
	recorder *MockDestroyConfigLoaderMockRecorder
	isgomock struct{}
}

// MockDestroyConfigLoaderMockRecorder is the mock recorder for MockDestroyConfigLoader.
type MockDestroyConfigLoaderMockRecorder struct {
	mock *MockDestroyConfigLoader
}

// NewMockDestroyConfigLoader creates a new mock instance.
func NewMockDestroyConfigLoader(ctrl *gomock.Controller) *MockDestroyConfigLoader {
	mock := &MockDestroyConfigLoader{ctrl: ctrl}
	mock.recorder = &MockDestroyConfigLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDestroyConfigLoader) EXPECT() *MockDestroyConfigLoaderMockRecorder {
	return m.recorder
}

// LoadFromConfig mocks base method.
func (m *MockDestroyConfigLoader) LoadFromConfig(cfg *config.EcosConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadFromConfig", cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadFromConfig indicates an expected call of LoadFromConfig.
func (mr *MockDestroyConfigLoaderMockRecorder) LoadFromConfig(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFromConfig", reflect.TypeOf((*MockDestroyConfigLoader)(nil).LoadFromConfig), cfg)
}

// MockDestroyPreviewer is a mock of DestroyPreviewer interface.
type MockDestroyPreviewer struct {
	ctrl     *gomock.Controller
	recorder *MockDestroyPreviewerMockRecorder
	isgomock struct{}
}

// MockDestroyPreviewerMockRecorder is the mock recorder for MockDestroyPreviewer.
type MockDestroyPreviewerMockRecorder struct {
	mock *MockDestroyPreviewer
}

// NewMockDestroyPreviewer creates a new mock instance.
func NewMockDestroyPreviewer(ctrl *gomock.Controller) *MockDestroyPreviewer {
	mock := &MockDestroyPreviewer{ctrl: ctrl}
	mock.recorder = &MockDestroyPreviewerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDestroyPreviewer) EXPECT() *MockDestroyPreviewerMockRecorder {
	return m.recorder
}

// DescribeDestruction mocks base method.
func (m *MockDestroyPreviewer) DescribeDestruction() []types.DestroyResourcePreview {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeDestruction")
	ret0, _ := ret[0].([]types.DestroyResourcePreview)
	return ret0
}

// DescribeDestruction indicates an expected call of DescribeDestruction.
func (mr *MockDestroyPreviewerMockRecorder) DescribeDestruction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDestruction", reflect.TypeOf((*MockDestroyPreviewer)(nil).DescribeDestruction))
}

// MockDestroyExecutor is a mock of DestroyExecutor interface.
type MockDestroyExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockDestroyExecutorMockRecorder
	isgomock struct{}
}

// MockDestroyExecutorMockRecorder is the mock recorder for MockDestroyExecutor.
type MockDestroyExecutorMockRecorder struct {
	mock *MockDestroyExecutor
}

// NewMockDestroyExecutor creates a new mock instance.
func NewMockDestroyExecutor(ctrl *gomock.Controller) *MockDestroyExecutor {
	mock := &MockDestroyExecutor{ctrl: ctrl}
	mock.recorder = &MockDestroyExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDestroyExecutor) EXPECT() *MockDestroyExecutorMockRecorder {
	return m.recorder
}

// DestroyResources mocks base method.
func (m *MockDestroyExecutor) DestroyResources() ([]types.DestroyResourceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyResources")
	ret0, _ := ret[0].([]types.DestroyResourceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DestroyResources indicates an expected call of DestroyResources.
func (mr *MockDestroyExecutorMockRecorder) DestroyResources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyResources", reflect.TypeOf((*MockDestroyExecutor)(nil).DestroyResources))
}
